server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/order_week_5
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    path match:
      matching-strategy: ant_path_matcher